"""foundation schema

Revision ID: 196dbb39ffb4
Revises:
Create Date: 2026-07-02 19:40:04.501873

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "196dbb39ffb4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspaces",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workspaces_slug"), "workspaces", ["slug"], unique=True)
    op.create_table(
        "projects",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=False)
    op.create_index(
        "ix_projects_workspace_created", "projects", ["workspace_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_projects_workspace_id"), "projects", ["workspace_id"], unique=False)
    op.create_table(
        "datasets",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=256), nullable=True),
        sa.Column("content_hash", sa.String(length=128), nullable=True),
        sa.Column("language_coverage", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_datasets_project_created", "datasets", ["project_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_datasets_project_id"), "datasets", ["project_id"], unique=False)
    op.create_table(
        "tts_models",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("provider", sa.String(length=160), nullable=True),
        sa.Column("model_family", sa.String(length=160), nullable=True),
        sa.Column("model_card_url", sa.String(length=512), nullable=True),
        sa.Column("license", sa.String(length=160), nullable=True),
        sa.Column("supported_languages", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_tts_models_project_created", "tts_models", ["project_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_tts_models_project_id"), "tts_models", ["project_id"], unique=False)
    op.create_table(
        "dataset_versions",
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("manifest_format", sa.String(length=16), nullable=False),
        sa.Column("manifest_hash", sa.String(length=128), nullable=True),
        sa.Column("manifest_json", sa.JSON(), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dataset_versions_dataset_id"), "dataset_versions", ["dataset_id"], unique=False
    )
    op.create_index(
        "ix_dataset_versions_dataset_version",
        "dataset_versions",
        ["dataset_id", "version"],
        unique=True,
    )
    op.create_table(
        "model_versions",
        sa.Column("model_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column("git_sha", sa.String(length=64), nullable=True),
        sa.Column("docker_image_tag", sa.String(length=256), nullable=True),
        sa.Column("configuration_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["tts_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_model_versions_model_id"), "model_versions", ["model_id"], unique=False
    )
    op.create_index(
        "ix_model_versions_model_version", "model_versions", ["model_id", "version"], unique=True
    )
    op.create_table(
        "dataset_items",
        sa.Column("dataset_version_id", sa.Uuid(), nullable=False),
        sa.Column("item_key", sa.String(length=160), nullable=False),
        sa.Column("expected_text", sa.Text(), nullable=False),
        sa.Column("normalized_expected_text", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("generated_audio_ref", sa.String(length=512), nullable=True),
        sa.Column("reference_audio_ref", sa.String(length=512), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["dataset_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dataset_items_dataset_version_id"),
        "dataset_items",
        ["dataset_version_id"],
        unique=False,
    )
    op.create_index("ix_dataset_items_language", "dataset_items", ["language"], unique=False)
    op.create_index(
        "ix_dataset_items_version_item",
        "dataset_items",
        ["dataset_version_id", "item_key"],
        unique=True,
    )
    op.create_table(
        "evaluation_runs",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_version_id", sa.Uuid(), nullable=False),
        sa.Column("model_version_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "QUEUED",
                "PREPARING",
                "RUNNING",
                "FINALIZING",
                "COMPLETED",
                "PARTIAL",
                "FAILED",
                "CANCELLED",
                name="runstatus",
            ),
            nullable=False,
        ),
        sa.Column("regression_decision", sa.String(length=16), nullable=True),
        sa.Column("selected_metrics", sa.JSON(), nullable=False),
        sa.Column("aggregate_metrics", sa.JSON(), nullable=False),
        sa.Column("immutable_manifest", sa.JSON(), nullable=False),
        sa.Column("execution_environment", sa.JSON(), nullable=False),
        sa.Column("total_items", sa.Integer(), nullable=False),
        sa.Column("processed_items", sa.Integer(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["dataset_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evaluation_runs_dataset_version_id"),
        "evaluation_runs",
        ["dataset_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evaluation_runs_model_version_id"),
        "evaluation_runs",
        ["model_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evaluation_runs_project_id"), "evaluation_runs", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_evaluation_runs_regression_decision"),
        "evaluation_runs",
        ["regression_decision"],
        unique=False,
    )
    op.create_index("ix_runs_created", "evaluation_runs", ["created_at"], unique=False)
    op.create_index("ix_runs_decision", "evaluation_runs", ["regression_decision"], unique=False)
    op.create_index(
        "ix_runs_project_status", "evaluation_runs", ["project_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_runs_project_status", table_name="evaluation_runs")
    op.drop_index("ix_runs_decision", table_name="evaluation_runs")
    op.drop_index("ix_runs_created", table_name="evaluation_runs")
    op.drop_index(op.f("ix_evaluation_runs_regression_decision"), table_name="evaluation_runs")
    op.drop_index(op.f("ix_evaluation_runs_project_id"), table_name="evaluation_runs")
    op.drop_index(op.f("ix_evaluation_runs_model_version_id"), table_name="evaluation_runs")
    op.drop_index(op.f("ix_evaluation_runs_dataset_version_id"), table_name="evaluation_runs")
    op.drop_table("evaluation_runs")
    op.drop_index("ix_dataset_items_version_item", table_name="dataset_items")
    op.drop_index("ix_dataset_items_language", table_name="dataset_items")
    op.drop_index(op.f("ix_dataset_items_dataset_version_id"), table_name="dataset_items")
    op.drop_table("dataset_items")
    op.drop_index("ix_model_versions_model_version", table_name="model_versions")
    op.drop_index(op.f("ix_model_versions_model_id"), table_name="model_versions")
    op.drop_table("model_versions")
    op.drop_index("ix_dataset_versions_dataset_version", table_name="dataset_versions")
    op.drop_index(op.f("ix_dataset_versions_dataset_id"), table_name="dataset_versions")
    op.drop_table("dataset_versions")
    op.drop_index(op.f("ix_tts_models_project_id"), table_name="tts_models")
    op.drop_index("ix_tts_models_project_created", table_name="tts_models")
    op.drop_table("tts_models")
    op.drop_index(op.f("ix_datasets_project_id"), table_name="datasets")
    op.drop_index("ix_datasets_project_created", table_name="datasets")
    op.drop_table("datasets")
    op.drop_index(op.f("ix_projects_workspace_id"), table_name="projects")
    op.drop_index("ix_projects_workspace_created", table_name="projects")
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_workspaces_slug"), table_name="workspaces")
    op.drop_table("workspaces")
    # ### end Alembic commands ###
