"""Phase 2 runtime, artifacts, evidence, and Listening Lab schema.

Revision ID: 5b4180d2e001
Revises: 196dbb39ffb4
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "5b4180d2e001"
down_revision: str | Sequence[str] | None = "196dbb39ffb4"
branch_labels = None
depends_on = None


def _uuid():
    return sa.Uuid()


def upgrade() -> None:
    with op.batch_alter_table("evaluation_runs") as batch:
        batch.add_column(sa.Column("rerun_of_id", _uuid(), nullable=True))
        batch.add_column(sa.Column("manifest_hash", sa.String(128), nullable=True))
        batch.add_column(sa.Column("execution_profile_id", sa.String(80), nullable=False, server_default="local-cpu-lightweight"))
        batch.add_column(sa.Column("cancellation_requested", sa.Boolean(), nullable=False, server_default=sa.false()))
        batch.add_column(sa.Column("current_stage", sa.String(64), nullable=True))
        batch.add_column(sa.Column("failure_reason", sa.Text(), nullable=True))
        batch.add_column(sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True))
        batch.create_foreign_key("fk_runs_rerun_of", "evaluation_runs", ["rerun_of_id"], ["id"])
    op.create_table("workers",sa.Column("worker_key",sa.String(160),nullable=False),sa.Column("profile_id",sa.String(80),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("capabilities_json",sa.JSON(),nullable=False),sa.Column("environment_json",sa.JSON(),nullable=False),sa.Column("last_heartbeat_at",sa.DateTime(timezone=True)),sa.Column("id",_uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("worker_key"))
    op.create_index("ix_workers_status_heartbeat","workers",["status","last_heartbeat_at"])
    op.create_table("evaluation_jobs",sa.Column("run_id",_uuid(),nullable=False),sa.Column("worker_id",_uuid()),sa.Column("idempotency_key",sa.String(200),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("attempt",sa.Integer(),nullable=False),sa.Column("retry_count",sa.Integer(),nullable=False),sa.Column("cancel_requested",sa.Boolean(),nullable=False),sa.Column("claimed_at",sa.DateTime(timezone=True)),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("finished_at",sa.DateTime(timezone=True)),sa.Column("error_message",sa.Text()),sa.Column("id",_uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["run_id"],["evaluation_runs.id"]),sa.ForeignKeyConstraint(["worker_id"],["workers.id"]),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("idempotency_key"),sa.UniqueConstraint("run_id","attempt",name="ix_jobs_run_attempt"))
    op.create_index("ix_jobs_status_created","evaluation_jobs",["status","created_at"])
    op.create_table("evaluation_events",sa.Column("run_id",_uuid(),nullable=False),sa.Column("job_id",_uuid()),sa.Column("sequence",sa.Integer(),nullable=False),sa.Column("event_type",sa.String(80),nullable=False),sa.Column("stage",sa.String(64)),sa.Column("level",sa.String(16),nullable=False),sa.Column("message",sa.Text(),nullable=False),sa.Column("payload_json",sa.JSON(),nullable=False),sa.Column("id",_uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["run_id"],["evaluation_runs.id"]),sa.ForeignKeyConstraint(["job_id"],["evaluation_jobs.id"]),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("run_id","sequence",name="ix_events_run_sequence"))
    op.create_table("evaluation_cases",sa.Column("run_id",_uuid(),nullable=False),sa.Column("dataset_item_id",_uuid(),nullable=False),sa.Column("sample_key",sa.String(160),nullable=False),sa.Column("language",sa.String(16),nullable=False),sa.Column("expected_text",sa.Text(),nullable=False),sa.Column("transcript",sa.Text()),sa.Column("status",sa.String(16),nullable=False),sa.Column("failure_reason",sa.Text()),sa.Column("reviewed_at",sa.DateTime(timezone=True)),sa.Column("review_note",sa.Text()),sa.Column("metric_summary_json",sa.JSON(),nullable=False),sa.Column("id",_uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["run_id"],["evaluation_runs.id"]),sa.ForeignKeyConstraint(["dataset_item_id"],["dataset_items.id"]),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("run_id","dataset_item_id",name="ix_cases_run_item"))
    op.create_index("ix_cases_run_status","evaluation_cases",["run_id","status"]);op.create_index("ix_cases_language","evaluation_cases",["language"])
    op.create_table("sample_metric_results",sa.Column("evaluation_case_id",_uuid(),nullable=False),sa.Column("metric_id",sa.String(100),nullable=False),sa.Column("metric_version",sa.String(32),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("value",sa.Float()),sa.Column("unit",sa.String(32)),sa.Column("confidence",sa.Float()),sa.Column("warnings",sa.JSON(),nullable=False),sa.Column("parameters_json",sa.JSON(),nullable=False),sa.Column("metadata_json",sa.JSON(),nullable=False),sa.Column("execution_duration_ms",sa.Integer(),nullable=False),sa.Column("error_message",sa.Text()),sa.Column("id",_uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["evaluation_case_id"],["evaluation_cases.id"]),sa.PrimaryKeyConstraint("id"))
    op.create_index("ix_metric_results_case_metric","sample_metric_results",["evaluation_case_id","metric_id"]);op.create_index("ix_metric_results_metric_status","sample_metric_results",["metric_id","status"])
    op.create_table("run_aggregate_metrics",sa.Column("run_id",_uuid(),nullable=False),sa.Column("metric_id",sa.String(100),nullable=False),sa.Column("metric_version",sa.String(32),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("sample_count",sa.Integer(),nullable=False),sa.Column("excluded_sample_count",sa.Integer(),nullable=False),sa.Column("mean",sa.Float()),sa.Column("median",sa.Float()),sa.Column("p95",sa.Float()),sa.Column("details_json",sa.JSON(),nullable=False),sa.Column("id",_uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["run_id"],["evaluation_runs.id"]),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("run_id","metric_id",name="ix_run_aggregate_metric"))
    op.create_table("artifacts",sa.Column("run_id",_uuid()),sa.Column("evaluation_case_id",_uuid()),sa.Column("kind",sa.String(20),nullable=False),sa.Column("storage_key",sa.String(768),nullable=False),sa.Column("content_hash",sa.String(128),nullable=False),sa.Column("content_type",sa.String(120),nullable=False),sa.Column("size_bytes",sa.Integer(),nullable=False),sa.Column("origin",sa.String(80),nullable=False),sa.Column("retention_policy",sa.String(80),nullable=False),sa.Column("id",_uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["run_id"],["evaluation_runs.id"]),sa.ForeignKeyConstraint(["evaluation_case_id"],["evaluation_cases.id"]),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("storage_key"))
    op.create_index("ix_artifact_hash","artifacts",["content_hash"]);op.create_index("ix_artifact_run_kind","artifacts",["run_id","kind"])
    op.create_table("baselines",sa.Column("project_id",_uuid(),nullable=False),sa.Column("run_id",_uuid(),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("is_frozen",sa.Boolean(),nullable=False),sa.Column("manifest_hash",sa.String(128)),sa.Column("id",_uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["project_id"],["projects.id"]),sa.ForeignKeyConstraint(["run_id"],["evaluation_runs.id"]),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("run_id"))
    op.create_table("regression_policies",sa.Column("project_id",_uuid(),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("metric_id",sa.String(100),nullable=False),sa.Column("metric_version",sa.String(32)),sa.Column("operator",sa.String(32),nullable=False),sa.Column("threshold",sa.Float(),nullable=False),sa.Column("severity",sa.String(16),nullable=False),sa.Column("baseline_id",_uuid()),sa.Column("language_filter",sa.String(16)),sa.Column("tag_filter",sa.String(100)),sa.Column("model_filter",sa.String(160)),sa.Column("execution_profile_filter",sa.String(80)),sa.Column("min_sample_count",sa.Integer(),nullable=False),sa.Column("confidence_required",sa.Float()),sa.Column("remediation_guidance",sa.Text()),sa.Column("enabled",sa.Boolean(),nullable=False),sa.Column("author",sa.String(160),nullable=False),sa.Column("id",_uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["project_id"],["projects.id"]),sa.ForeignKeyConstraint(["baseline_id"],["baselines.id"]),sa.PrimaryKeyConstraint("id"))
    op.create_table("regression_results",sa.Column("run_id",_uuid(),nullable=False),sa.Column("policy_id",_uuid(),nullable=False),sa.Column("integrity_status",sa.String(40),nullable=False),sa.Column("decision",sa.String(24),nullable=False),sa.Column("observed_value",sa.Float()),sa.Column("baseline_value",sa.Float()),sa.Column("absolute_delta",sa.Float()),sa.Column("relative_delta",sa.Float()),sa.Column("confidence_interval_json",sa.JSON(),nullable=False),sa.Column("sample_count",sa.Integer(),nullable=False),sa.Column("excluded_sample_count",sa.Integer(),nullable=False),sa.Column("explanation",sa.Text(),nullable=False),sa.Column("affected_samples_json",sa.JSON(),nullable=False),sa.Column("id",_uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["run_id"],["evaluation_runs.id"]),sa.ForeignKeyConstraint(["policy_id"],["regression_policies.id"]),sa.PrimaryKeyConstraint("id"))
    op.create_table("comparisons",sa.Column("candidate_run_id",_uuid(),nullable=False),sa.Column("baseline_run_id",_uuid(),nullable=False),sa.Column("integrity_status",sa.String(40),nullable=False),sa.Column("integrity_reasons",sa.JSON(),nullable=False),sa.Column("verdict",sa.String(48),nullable=False),sa.Column("methodology_json",sa.JSON(),nullable=False),sa.Column("id",_uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["candidate_run_id"],["evaluation_runs.id"]),sa.ForeignKeyConstraint(["baseline_run_id"],["evaluation_runs.id"]),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("candidate_run_id","baseline_run_id",name="ix_comparisons_runs"))
    op.create_table("comparison_metric_results",sa.Column("comparison_id",_uuid(),nullable=False),sa.Column("metric_id",sa.String(100),nullable=False),sa.Column("baseline_value",sa.Float()),sa.Column("candidate_value",sa.Float()),sa.Column("absolute_delta",sa.Float()),sa.Column("relative_delta",sa.Float()),sa.Column("confidence_interval_json",sa.JSON(),nullable=False),sa.Column("sample_count",sa.Integer(),nullable=False),sa.Column("verdict",sa.String(48),nullable=False),sa.Column("id",_uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["comparison_id"],["comparisons.id"]),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("comparison_id","metric_id",name="ix_compare_metric"))
    op.create_table("benchmark_cards",sa.Column("run_id",_uuid(),nullable=False),sa.Column("integrity_status",sa.String(40),nullable=False),sa.Column("manifest_hash",sa.String(128)),sa.Column("content_json",sa.JSON(),nullable=False),sa.Column("markdown",sa.Text(),nullable=False),sa.Column("html",sa.Text(),nullable=False),sa.Column("id",_uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["run_id"],["evaluation_runs.id"]),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("run_id",name="ix_benchmark_cards_run"))
    op.create_table("listening_studies",sa.Column("project_id",_uuid(),nullable=False),sa.Column("title",sa.String(200),nullable=False),sa.Column("description",sa.Text()),sa.Column("state",sa.String(24),nullable=False),sa.Column("test_type",sa.String(24),nullable=False),sa.Column("linked_run_ids",sa.JSON(),nullable=False),sa.Column("selected_sample_keys",sa.JSON(),nullable=False),sa.Column("rating_scale",sa.JSON(),nullable=False),sa.Column("rater_instructions",sa.Text()),sa.Column("consent_notice",sa.Text()),sa.Column("randomization_seed",sa.Integer(),nullable=False),sa.Column("anonymity_enabled",sa.Boolean(),nullable=False),sa.Column("response_limit",sa.Integer()),sa.Column("data_retention",sa.String(80),nullable=False),sa.Column("created_by",sa.String(160),nullable=False),sa.Column("id",_uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["project_id"],["projects.id"]),sa.PrimaryKeyConstraint("id"))
    op.create_table("listening_tasks",sa.Column("study_id",_uuid(),nullable=False),sa.Column("task_order",sa.Integer(),nullable=False),sa.Column("sample_key",sa.String(160),nullable=False),sa.Column("expected_text",sa.Text()),sa.Column("option_a_json",sa.JSON(),nullable=False),sa.Column("option_b_json",sa.JSON(),nullable=False),sa.Column("option_x_json",sa.JSON(),nullable=False),sa.Column("randomization_token",sa.String(128),nullable=False),sa.Column("id",_uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["study_id"],["listening_studies.id"]),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("study_id","task_order",name="ix_listening_tasks_study_order"))
    op.create_table("listening_responses",sa.Column("study_id",_uuid(),nullable=False),sa.Column("task_id",_uuid(),nullable=False),sa.Column("rater_key",sa.String(160),nullable=False),sa.Column("preference",sa.String(24)),sa.Column("rating",sa.Float()),sa.Column("confidence",sa.Integer()),sa.Column("note",sa.Text()),sa.Column("duration_ms",sa.Integer()),sa.Column("is_complete",sa.Boolean(),nullable=False),sa.Column("id",_uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["study_id"],["listening_studies.id"]),sa.ForeignKeyConstraint(["task_id"],["listening_tasks.id"]),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("study_id","task_id","rater_key",name="ix_listening_response_unique"))


def downgrade() -> None:
    # Destructive downgrade intentionally removes only Phase 2 tables; retained run columns are removed in batch mode.
    for table in ["listening_responses","listening_tasks","listening_studies","benchmark_cards","comparison_metric_results","comparisons","regression_results","regression_policies","baselines","artifacts","run_aggregate_metrics","sample_metric_results","evaluation_cases","evaluation_events","evaluation_jobs","workers"]:
        op.drop_table(table)
    with op.batch_alter_table("evaluation_runs") as batch:
        for column in ["completed_at","failure_reason","current_stage","cancellation_requested","execution_profile_id","manifest_hash","rerun_of_id"]:
            batch.drop_column(column)
